server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: C:\InSights\Development\promtail\promtail-windows\positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push
    tenant_id: "machine1"

scrape_configs:
  - job_name: platformEngine
    static_configs:
      - targets:
          - localhost
      - labels:
          __path__: "C:/InSights/Insights_Deployment/Server2/INSIGHTS_HOME/logs/PlatformEngine/platformEngine77.log"
          job: PlatformEngine
          tenant_id: machine1
      
    pipeline_stages:      
      - match:
          selector: '{job="PlatformEngine"} |="StatisticsImpl"'
          stages:
            - regex:
                expression: "(?s)(HQL\\:) (?P<HQL>(.+?)), (time\\:) (?P<processingtime>(.+?))ms, (rows\\:) (?P<rowsCount>(.+?))"
            - labels:
                HQL:
                processingtime:
                rowsCount:
               
  - job_name: PlatformAgent
    static_configs:
      - targets:
          - localhost
      - labels:
          __path__: "C:/InSights/Insights_Deployment/Server2/INSIGHTS_HOME/logs/PlatformAgent/log_*.log"
          job: PlatformAgent
          tenant_id: machine1
          
    pipeline_stages:      
      - match:
          selector: '{job="PlatformAgent"}'
          stages:
            - regex:
                expression: "^(?s)t=(?P<time>\\S+\\s\\S+)\\slvl=(?P<level>\\S+)\\sfilename=(?P<filename>\\S+)\\sfuncName=(?P<funcName>\\S+)\\slineno=(?P<lineno>\\S+)\\stoolName=(?P<toolName>\\S+)\\sagentId=(?P<agentId>\\S+)\\sexecId=(?P<execId>\\S+)\\smessage=(?P<message>(.+\\s))?"
            - labels:
                time:
                level:
                filename:
                funcName:
                lineno:
                toolName:
                agentId:
                execId:
                message:
                
  - job_name: PlatformService
    static_configs:
      - targets:
          - localhost
      - labels:
          __path__: "C:/InSights/Insights_Deployment/Server2/INSIGHTS_HOME/logs/PlatformService/platformService.log"
          job: PlatformService
          tenant_id: machine1
      
    pipeline_stages:      
      - match:
          selector: '{job="PlatformService"}'
          stages:
            - regex:
                expression: "^(?s)t=(?P<time>\\S+\\s\\S+)\\slvl=(?P<level>\\S+)\\sfileName=(?P<fileName>\\S+)\\smethodName=(?P<methodName>\\S+)\\slineno=(?P<lineno>\\S+)\\s(?:(Type)=(?P<Type>(.\\S+))\\s)?(?:(traceId)=(?P<traceId>(.\\S*))\\s)?(?:(method)=(?P<method>(.\\S*))\\s)?(?:(endpoint)=(?P<endpoint>(.\\S*))\\s)?(?:(processingTime)=(?P<processingTime>(.\\S*))\\s)?(?:(message)=(?P<message>(.*)))?"
            - labels:
                time:
                level:
                fileName:
                methodName:
                lineno:
                Type:
                traceId:
                method:
                endpoint:
                processingTime:
                message:

target_config:
    sync_period: "10s"